version: "3.9"

services:

  db:
    image: postgres:15
    networks:
      - booking_network
    env_file:
      - ./db/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      timeout: 5s

  web:
    image: booking-backend:latest
    networks:
      - booking_network
    env_file:
      - ./db/.env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    image: booking-frontend:latest
    networks:
      - booking_network
    depends_on:
      - web
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.25
    networks:
      - booking_network
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - web
    deploy:
      restart_policy:
        condition: on-failure

networks:
  booking_network:
    driver: overlay

volumes:
  pgdata:
