version: "3.8"

services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-tourdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  web:
    # backend service (Flask)
    build: ./backend
    image: booking-backend
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/tourdb}
    ports:
      - target: 8000
        published: 8000
        mode: host
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    image: booking-frontend
    ports:
      - target: 80
        published: 80
        mode: host
    depends_on:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
